// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACb0dPI0Tg8h-K-by2kbpfN5nq9-j6YDM',
    appId: '1:48501856424:web:053a0e3d8a1ce59d5e0a9d',
    messagingSenderId: '48501856424',
    projectId: 'fridgeminii',
    authDomain: 'fridgeminii.firebaseapp.com',
    storageBucket: 'fridgeminii.firebasestorage.app',
    measurementId: 'G-5W82C6EPEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg9MA9zkzvJK819Dhd2DnuTiExSv1X3jI',
    appId: '1:48501856424:android:bbad5b22dac834095e0a9d',
    messagingSenderId: '48501856424',
    projectId: 'fridgeminii',
    storageBucket: 'fridgeminii.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeQIE9_EtiK_SyNhqkNQTpw1r47GUxi2c',
    appId: '1:48501856424:ios:f1491ddd8d5496965e0a9d',
    messagingSenderId: '48501856424',
    projectId: 'fridgeminii',
    storageBucket: 'fridgeminii.firebasestorage.app',
    iosBundleId: 'com.example.fridgemini',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeQIE9_EtiK_SyNhqkNQTpw1r47GUxi2c',
    appId: '1:48501856424:ios:f1491ddd8d5496965e0a9d',
    messagingSenderId: '48501856424',
    projectId: 'fridgeminii',
    storageBucket: 'fridgeminii.firebasestorage.app',
    iosBundleId: 'com.example.fridgemini',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACb0dPI0Tg8h-K-by2kbpfN5nq9-j6YDM',
    appId: '1:48501856424:web:6f1e785cd2a7649d5e0a9d',
    messagingSenderId: '48501856424',
    projectId: 'fridgeminii',
    authDomain: 'fridgeminii.firebaseapp.com',
    storageBucket: 'fridgeminii.firebasestorage.app',
    measurementId: 'G-VBDGXSCZ63',
  );

}